# Generated by Django 5.1.7 on 2025-03-26 19:18

import django.db.models.deletion
import django.utils.timezone
import lakkhi_app.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=2, null=True)),
                ('name', models.CharField(max_length=254, null=True)),
                ('nicename', models.CharField(max_length=254, null=True)),
                ('iso3', models.CharField(max_length=3, null=True)),
                ('numcode', models.IntegerField(null=True)),
                ('phonecode', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EligibleCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=2, null=True)),
                ('name', models.CharField(max_length=254, null=True)),
                ('nicename', models.CharField(max_length=254, null=True)),
                ('iso3', models.CharField(max_length=3, null=True)),
                ('numcode', models.IntegerField(null=True)),
                ('phonecode', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('wallet_address', models.CharField(max_length=254)),
                ('token_address', models.CharField(max_length=254)),
                ('blockchain_chain', models.CharField(default='BSC', max_length=50)),
                ('fund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('number_of_donators', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RSVPSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('email', lakkhi_app.models.LowerCaseCharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', lakkhi_app.models.LowerCaseCharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=lakkhi_app.models.get_users_files_directory)),
                ('bio', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('total_contributions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('password_reset_token', models.CharField(blank=True, max_length=254, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=lakkhi_app.models.get_project_files_directory)),
                ('file_type', models.CharField(blank=True, max_length=254, null=True)),
                ('file_name', models.CharField(blank=True, max_length=254, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lakkhi_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, null=True, unique=True)),
                ('thumbnail', models.ImageField(default='help.jpg', null=True, upload_to=lakkhi_app.models.get_project_files_directory)),
                ('info', models.TextField(max_length=1000, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('event_date', models.DateTimeField(null=True)),
                ('approved', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='rsvp_subscribed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lakkhi_app.category')),
            ],
        ),
    ]
